#**NUMPY ARRAY**

In [ ]:
import numpy as np
import sys

# BASIC NUMPY ARRAYS
array trong numpy được sử dụng để tạo ra một mảng dữ liệu từ list [], tuple ()hoặc dạng dữ liệu tương tự

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
print(a[0], a[1])

1 2


In [ ]:
print(a[0:]) # từ số đầu tiên đến cuối cùng

[1 2 3 4]


In [ ]:
print(a[1:3]) # từ số vị trí 1 đến số vị trí 3-1

[2 3]


In [ ]:
print(a[1:-1]) # từ số vị trí 1 đến số vị trí -1-1

[2 3]


In [ ]:
a.dtype # kiểu array

dtype('int64')

In [ ]:
np.array(a, dtype=float) # đổi kiểu

array([1., 2., 3., 4.])

In [ ]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b.shape # dạng 2 dòng 3 cột

(2, 3)

In [ ]:
b.ndim # dimension, chiều dữ liệu (hàng) = 2

2

In [ ]:
b.size # số lượng phần tử = 6

6

In [ ]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[9,10,11]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 9 10 11]]]


In [ ]:
c.shape

(2, 2, 3)

In [ ]:
c.ndim

3

In [ ]:
c.size

12

##INDEXING AND SLICING OF MATRICES

In [ ]:
# Square matric
matric = np.array([[1,2,3],[4,5,6],[7,8,9]])
matric

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matric[1] # hàng thứ 1

array([4, 5, 6])

In [ ]:
print(matric[1][0]) # hàng thứ 1, cột số 0 => 4 cách khác: print(matric[1,0])

4


In [ ]:
print(matric[0:2]) # hàng thứ 0 đến hàng thứ 2-1

[[1 2 3]
 [4 5 6]]


In [ ]:
print(matric[:,:2]) # tất cả các hàng, từ cột 0 đến cột 2-1

[[1 2]
 [4 5]
 [7 8]]


In [ ]:
matric[1] = np.array([1,4,8]) # thay hàng thứ 1 bằng [1,4,8]
matric

array([[1, 2, 3],
       [1, 4, 8],
       [7, 8, 9]])

In [ ]:
matric[2] = 0 # thay tất cả giá trị ở hàng thứ 2 bằng 0
matric

array([[1, 2, 3],
       [1, 4, 8],
       [0, 0, 0]])

##SUMARY STATISTIC

In [ ]:
d = np.array([1,2,3,4,5,6,7])
print(d)

[1 2 3 4 5 6 7]


In [ ]:
print(d.sum()) # tổng tất cả số trong d

28


In [ ]:
print(d.mean())

4.0


In [ ]:
print(d.std())

2.0


In [ ]:
print(d.var())

4.0


In [ ]:
e = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(e)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [ ]:
print(e.sum(axis=0)) #cộng theo hàng dọc
print(e.sum(axis=1)) #cộng theo hàng ngang

[35 40 45]
[ 6 15 24 33 42]


In [ ]:
print(e.mean(axis=0))
print(e.mean(axis=1))

[7. 8. 9.]
[ 2.  5.  8. 11. 14.]


In [ ]:
print(e.std(axis=0))
print(e.std(axis=1))

[4.24264069 4.24264069 4.24264069]
[0.81649658 0.81649658 0.81649658 0.81649658 0.81649658]


In [ ]:
print(e.var(axis=0))
print(e.var(axis=1))

[18. 18. 18.]
[0.66666667 0.66666667 0.66666667 0.66666667 0.66666667]


##BROADCASTING AND VECTORIZED OPRATIONS

In [ ]:
f=np.arange(4)
print(f)
print(f+10)
print(f*10)
print(f/10)

[0 1 2 3]
[10 11 12 13]
[ 0 10 20 30]
[0.  0.1 0.2 0.3]


In [ ]:
g = list(int(i)*10 for i in f)
print(g) # ban đầu sẽ ko ra số trực tiếp do là array phải định dạng i bằng int

[0, 10, 20, 30]


In [ ]:
f+g

array([ 0, 11, 22, 33])

##BOOLEAN ARRAYS

In [ ]:
h = np.array([11,22,33,44,55])
print(h)

[11 22 33 44 55]


In [ ]:
h[[True, False, False, True,True]] # không in những thành phần được đánh là False

array([11, 44, 55])

In [ ]:
h>=34

array([False, False, False,  True,  True])

In [ ]:
h[h>34]

array([44, 55])

In [ ]:
print(h[(h == 22) | (h == 11)])

[11 22]


In [ ]:
h[h > h.mean()]

array([44, 55])

In [ ]:
h[(h <= 44) & (h % 2 == 0)]

array([22, 44])

##LINEAR ALGEBRA

In [ ]:
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [ ]:
B = np.array ([[6,5],[4,3],[2,1]])

In [ ]:
A.dot(B) # nhân ma trận

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
A@B # nhân ma trận

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
B.T # ma trận chuyển vị

array([[1, 4],
       [2, 5],
       [3, 6]])

##SIZE OF OBJECTS IN MEMORY

*   an integer in python is > 24 bytes
*   longs are even larger
*   Numpy size is much smaller
*   Lists are even larger






In [ ]:
sys.getsizeof(1)

28

In [ ]:
sys.getsizeof(10**90)

64

In [ ]:
np.dtype(int).itemsize

8

In [ ]:
np.dtype(np.int8).itemsize

1

In [ ]:
np.dtype(float).itemsize

8

In [ ]:
sys.getsizeof([1])

64

In [ ]:
np.array([1]).nbytes

8

Performance

In [ ]:
l = list(range(100000))
%time sum([x ** 2 for x in l])

CPU times: user 17.2 ms, sys: 876 µs, total: 18.1 ms
Wall time: 27 ms


333328333350000

In [ ]:
k = np.arange(100000)
%time sum(a**2)

CPU times: user 101 µs, sys: 0 ns, total: 101 µs
Wall time: 107 µs


np.int64(30)